export type ProductType =
  | "zip"
  | "intake"
  | "bundle"
  | "subscription"
  | "subscription-intake";

export type ProductCategory =
  | "ai-agents"
  | "devops"
  | "automation"
  | "saas"
  | "bundles"
  | "community";

export interface Product {
  slug: string;
  name: string;
  price: number;
  type: ProductType;
  category: ProductCategory;
  badge: string;
  description: string;
  whopUrl: string;
  featured: boolean;
  bundleIncludes?: string[];
}

export const PRODUCTS: Product[] = [
  {
    slug: "ai-agent-pack",
    name: "AI Agent Pack — Full Library",
    price: 4900,
    type: "zip",
    category: "ai-agents",
    badge: "ZIP",
    description:
      "144 specialized AI agents organized by domain. Engineering, marketing, DevOps, sales, finance, game dev. Works with Claude Code, Copilot, Cursor, Windsurf, Aider.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: true,
  },
  {
    slug: "claude-code-agent-pack",
    name: "Claude Code Agent Pack",
    price: 7900,
    type: "zip",
    category: "ai-agents",
    badge: "ZIP",
    description:
      "Curated Claude Code agents for engineering, testing, and specialized workflows. Includes install.sh for one-command setup.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "devops-starter-kit",
    name: "DevOps Starter Kit",
    price: 5900,
    type: "zip",
    category: "devops",
    badge: "ZIP",
    description:
      "CI/CD templates, Docker configs, Hetzner + Cloudflare setup guides, monitoring checklists. Production-ready from day one.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "make-scenario-pack",
    name: "Make.com Automation Scenario Pack",
    price: 7900,
    type: "zip",
    category: "automation",
    badge: "ZIP",
    description:
      "Ready-to-import Make.com scenarios for lead nurture, content publishing, product delivery, and CRM automation.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "whop-agency-kit",
    name: "Whop Agency Setup Kit",
    price: 9900,
    type: "zip",
    category: "automation",
    badge: "ZIP",
    description:
      "Everything to launch a Whop digital product store. Webhook setup, product templates, pricing strategy doc, affiliate config guide.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "infra-audit",
    name: "AI Infrastructure Audit",
    price: 9900,
    type: "intake",
    category: "devops",
    badge: "AI Report",
    description:
      "Submit your server details. Claude analyzes your infrastructure and delivers a risk-scored PDF audit with prioritized remediation roadmap. Delivered within minutes.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: true,
  },
  {
    slug: "saas-boilerplate",
    name: "Next.js 15 SaaS Boilerplate",
    price: 14900,
    type: "zip",
    category: "saas",
    badge: "ZIP",
    description:
      "Production-ready Next.js 15 starter. App Router, Bun, Tailwind v4, Prisma on Neon, NextAuth v5, Stripe billing, R2 storage. Deploy to Vercel in 10 minutes.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: true,
  },
  {
    slug: "automation-spec-doc",
    name: "Automation Spec Doc",
    price: 5900,
    type: "intake",
    category: "automation",
    badge: "AI Report",
    description:
      "Describe your manual process. Claude produces a full Make.com scenario blueprint with module sequence, API requirements, and build estimate.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "community",
    name: "Autonomous Founder Systems Community",
    price: 2900,
    type: "subscription",
    category: "community",
    badge: "Monthly",
    description:
      "Private community for founders building zero-human systems. New content every Monday. Tools, automation workflows, and direct access.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "managed-devops",
    name: "Managed DevOps Monthly Report",
    price: 19900,
    type: "subscription-intake",
    category: "devops",
    badge: "Monthly",
    description:
      "Monthly PDF infrastructure health report. SSL checks, uptime analysis, cost recommendations. Generated by AI from your monitoring data.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "notion-founder-os",
    name: "Notion Founder OS Template",
    price: 2900,
    type: "zip",
    category: "saas",
    badge: "ZIP",
    description:
      "Complete Notion workspace for solo founders. CRM, project tracker, revenue dashboard, content calendar, OKR system. Duplicate and go.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
  },
  {
    slug: "automation-launch-bundle",
    name: "Automation Launch Bundle",
    price: 24900,
    type: "bundle",
    category: "bundles",
    badge: "Bundle",
    description:
      "SaaS Boilerplate + AI Agent Pack + Make Scenario Pack + DevOps Kit. Everything to launch an automated product business.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
    bundleIncludes: [
      "saas-boilerplate",
      "ai-agent-pack",
      "make-scenario-pack",
      "devops-starter-kit",
    ],
  },
  {
    slug: "agency-operator-bundle",
    name: "Agency Operator Bundle",
    price: 14900,
    type: "bundle",
    category: "bundles",
    badge: "Bundle",
    description:
      "Whop Agency Kit + Make Scenario Pack + AI Agent Pack. Built for operators running client automation workflows.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
    bundleIncludes: ["whop-agency-kit", "make-scenario-pack", "ai-agent-pack"],
  },
  {
    slug: "developer-ai-toolkit",
    name: "Developer AI Toolkit",
    price: 12900,
    type: "bundle",
    category: "bundles",
    badge: "Bundle",
    description:
      "Claude Code Pack + DevOps Kit + SaaS Boilerplate. The complete engineering stack for AI-native developers.",
    whopUrl: "https://whop.com/rihan-consulting/",
    featured: false,
    bundleIncludes: ["claude-code-agent-pack", "devops-starter-kit", "saas-boilerplate"],
  },
];

export const CATEGORY_LABELS: Record<ProductCategory, string> = {
  "ai-agents": "AI Agents",
  devops: "DevOps",
  automation: "Automation",
  saas: "SaaS",
  bundles: "Bundles",
  community: "Community",
};

export const PRODUCT_DETAILS: Record<
  string,
  { longDescription: string; includes: string[] }
> = {
  "ai-agent-pack": {
    longDescription:
      "The full library of 144 AI agents, organized by domain and ready for real work. Each agent ships with a focused role definition and guardrails so outputs stay sharp and consistent. Drop them into Claude Code, Copilot, Cursor, Windsurf, or Aider and get production-grade results fast. Built for founders who want leverage without headcount.",
    includes: [
      "144 role-based agents across engineering, marketing, sales, finance, DevOps, and game dev",
      "Structured prompts with guardrails for repeatable output",
      "Compatibility with Claude Code, Copilot, Cursor, Windsurf, and Aider",
      "Instant ZIP download with 48-hour link",
    ],
  },
  "claude-code-agent-pack": {
    longDescription:
      "A curated Claude Code collection designed for engineering teams that want speed with correctness. Each agent is tuned for a specific workflow: implementation, debugging, testing, refactoring, and review. The pack includes a one-command installer so you can wire it into your repo in minutes. No fluff, just focused execution.",
    includes: [
      "Claude Code agents for build, test, debug, and refactor workflows",
      "Install script for one-command setup",
      "Usage notes and workflow recommendations",
      "Instant ZIP download with 48-hour link",
    ],
  },
  "devops-starter-kit": {
    longDescription:
      "A production-grade DevOps foundation you can deploy immediately. From CI/CD pipelines to Docker production configs, every piece is battle-tested and documented. The kit includes Hetzner and Cloudflare setup guides plus monitoring checklists that map to real ops playbooks. Build once, then scale safely.",
    includes: [
      "CI/CD templates with GitHub Actions",
      "Docker and production deployment configs",
      "Hetzner + Cloudflare setup guides",
      "Monitoring and incident checklists",
    ],
  },
  "make-scenario-pack": {
    longDescription:
      "Pre-built Make.com scenarios that cover your most valuable automations. Import and run flows for lead capture, CRM sync, content publishing, and product delivery. Each scenario includes clear inputs, outputs, and module order so you can customize fast. Designed to ship revenue workflows in hours, not weeks.",
    includes: [
      "Lead nurture + onboarding scenarios",
      "Content publishing automation",
      "Digital product delivery flows",
      "CRM and notification sync modules",
    ],
  },
  "whop-agency-kit": {
    longDescription:
      "Launch a Whop digital product store without guesswork. This kit includes the webhook setup, product templates, pricing guidance, and affiliate config you need to go live. Built for operators who want a repeatable launch playbook. Everything is organized so you can deploy in a single weekend.",
    includes: [
      "Webhook setup and validation checklist",
      "Product template library and pricing strategy",
      "Affiliate configuration guide",
      "Launch SOP and delivery workflow",
    ],
  },
  "infra-audit": {
    longDescription:
      "Submit your infrastructure details and receive a risk-scored AI audit within minutes. The report surfaces security gaps, reliability risks, and cost leaks with clear remediation steps. It is engineered for busy founders who need actionable fixes, not vague advice. Delivered as a PDF with an executive summary and roadmap.",
    includes: [
      "Risk score with prioritized remediation list",
      "Security, reliability, and cost findings",
      "Executive summary + roadmap sections",
      "PDF delivery within minutes after intake",
    ],
  },
  "saas-boilerplate": {
    longDescription:
      "A production-ready Next.js 15 SaaS foundation built on the exact stack used in this platform. App Router, Bun, Tailwind v4, Prisma on Neon, NextAuth v5, Stripe billing, and R2 storage are pre-wired. Spin up a real SaaS in under 10 minutes. No scaffolding busywork, just ship.",
    includes: [
      "App Router + Bun + Tailwind v4 setup",
      "Prisma on Neon + NextAuth v5 wired in",
      "Stripe billing flows",
      "R2 storage integration",
    ],
  },
  "automation-spec-doc": {
    longDescription:
      "Describe your manual process and receive a Make.com scenario blueprint that you can build immediately. The spec includes module order, API requirements, inputs, outputs, and build effort. It is designed for founders who want clarity before implementation. Delivered fast with no back-and-forth.",
    includes: [
      "Module-by-module Make.com blueprint",
      "API requirements checklist",
      "Input/output mapping",
      "Estimated build effort and caveats",
    ],
  },
  community: {
    longDescription:
      "A private community for builders shipping zero-human systems. Every Monday you get fresh workflows, tools, and operator notes. The focus is execution, not hype. If you want direct access to how this stack is built, this is the room.",
    includes: [
      "Weekly drops every Monday",
      "Private community access",
      "Automation workflows and tools",
      "Operator updates from Rihan",
    ],
  },
  "managed-devops": {
    longDescription:
      "A monthly, AI-generated infrastructure report based on your monitoring data. You get SSL status, uptime analysis, cost recommendations, and a clear action list. This is for founders who want ops visibility without hiring a full team. Delivered every month as a PDF.",
    includes: [
      "Monthly PDF infrastructure health report",
      "SSL, uptime, and cost findings",
      "Actionable recommendations",
      "Delivered automatically every month",
    ],
  },
  "notion-founder-os": {
    longDescription:
      "A complete Notion workspace designed for solo founders. Manage pipeline, projects, revenue, and content without building from scratch. The template is clean, fast to duplicate, and easy to extend. It is the operating system for your day-to-day execution.",
    includes: [
      "CRM and sales pipeline tracker",
      "Project and delivery dashboard",
      "Revenue reporting views",
      "Content calendar and OKR system",
    ],
  },
  "automation-launch-bundle": {
    longDescription:
      "The full launch stack for automated product businesses. You get the SaaS Boilerplate, AI Agent Pack, Make Scenario Pack, and DevOps Starter Kit in one bundle. It is built for founders who want to ship fast and avoid tool sprawl. One purchase, full stack.",
    includes: [
      "Next.js 15 SaaS Boilerplate",
      "AI Agent Pack — Full Library",
      "Make.com Automation Scenario Pack",
      "DevOps Starter Kit",
    ],
  },
  "agency-operator-bundle": {
    longDescription:
      "A focused operator bundle for agencies running client automation. It combines the Whop Agency Kit, Make Scenario Pack, and AI Agent Pack for end-to-end delivery. Everything is pre-structured to help you deploy faster, onboard clients, and fulfill instantly. Built for scale without extra hires.",
    includes: [
      "Whop Agency Setup Kit",
      "Make.com Automation Scenario Pack",
      "AI Agent Pack — Full Library",
    ],
  },
  "developer-ai-toolkit": {
    longDescription:
      "A complete engineering stack for AI-native developers. This bundle combines the Claude Code Pack, DevOps Starter Kit, and SaaS Boilerplate. It is optimized for building, testing, and shipping production SaaS quickly. One bundle, no missing pieces.",
    includes: [
      "Claude Code Agent Pack",
      "DevOps Starter Kit",
      "Next.js 15 SaaS Boilerplate",
    ],
  },
};

export function formatPrice(cents: number): string {
  return (cents / 100).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
  });
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((product) => product.slug === slug);
}

export function getBadgeClasses(badge: string): string {
  switch (badge) {
    case "ZIP":
      return "border-blue-500/30 bg-blue-500/10 text-blue-300";
    case "AI Report":
      return "border-amber-500/30 bg-amber-500/10 text-amber-300";
    case "Bundle":
      return "border-purple-500/30 bg-purple-500/10 text-purple-300";
    case "Monthly":
      return "border-[#4f98a3]/40 bg-[#4f98a3]/10 text-[#7ed6df]";
    default:
      return "border-[#2e2d2a] bg-[#232220] text-[#c9c7c0]";
  }
}

export function getDeliveryNote(type: ProductType): string {
  switch (type) {
    case "zip":
    case "bundle":
      return "Delivered via secure 48h download link";
    case "intake":
      return "Intake form sent after purchase";
    case "subscription":
    case "subscription-intake":
      return "Billed monthly";
    default:
      return "Instant delivery";
  }
}

export function getBundleValue(slug: string): number | null {
  const product = getProductBySlug(slug);
  if (!product?.bundleIncludes) return null;
  return product.bundleIncludes.reduce((total, includeSlug) => {
    const included = getProductBySlug(includeSlug);
    return included ? total + included.price : total;
  }, 0);
}
